<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="NewForm.aspx.cs" Inherits="SignalRChat.NewForm" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<!DOCTYPE html>

<html
  class="js serviceworker adownload cssanimations csstransitions webp webp-alpha webp-animation webp-lossless"
  dir="LTR"
  loc="en-GB"
  lang="en"
>
  <head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title><%=Session["UserName"] %></title>
    <meta name="viewport" content="width=device-width" />
    <meta name="google" content="notranslate" />
    <meta name="format-detection" content="telephone=no" />
    <meta
      name="description"
      content="Quickly send and receive WhatsApp messages right from your computer."
    />
    <meta
      name="og:description"
      content="Quickly send and receive WhatsApp messages right from your computer."
    />
    <meta name="og:url" content="https://web.whatsapp.com/" />
    <meta name="og:title" content="WhatsApp Web" />
    
    
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">


          <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
   
      

    <script src="Scripts/jQuery-3.2.1.min.js"></script>
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="Scripts/date.format.js"></script>

    <!--EmojiOneArea
    <link href="Content/emojionearea.min.css" rel="stylesheet" />
    <script src="Scripts/emojionearea.js"></script>
       -->
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Jquery slimScroll -->
    <script type="text/javascript" src="Scripts/jquery.slimscroll.min.js"></script>
    <script type="text/javascript" src="Scripts/connection.js"></script>
   
    <script src="Scripts/jquery-ui-1.12.1.js"></script>
    <%-- <script type="text/javascript" src="js\registerclientmethods"></script>
   <script type="text/javascript" src="js\registerevents"></script>--%>






      <script type="text/javascript" src="js/JavaScript1.js"></script>
    <script type="text/javascript">


        
        function registerEvents(chatHub) {

           


            $(document).ready(function () {
                var selectedfield = 'c';
                var name = '<%# this.UserName %>';
                var badge = '<%# this.UserBadge %>';
                var enrollno = '<%# this.UserEnrollNo %>';
                var department = '<%# this.UserDepartment %>';
                var email = '<%# this.UserEmail %>';
                var toGroupId;


                if (name.length > 0) {
                    chatHub.server.connect(name, badge, enrollno, department, email);

                }

    
                
          
   // Send Button Click Event
            $('#btnSendMsg').click(  function () {

                var msg = $("#txtMessage").html();
                $("#txtMessage").html('');

                if (msg.length > 0) {
                    var fromUserName = name;
                    var fromuserEnroll = $('#hdUserEnroll').val();
                    var toUserEnroll = $('#hdtoUserEnroll').val();
                
                    
                    switch (selectedfield) {
                        case 'c':
                            chatHub.server.sendPrivateMessage(fromUserName, fromuserEnroll, toUserEnroll, msg);
                            console.log('server request sent');
                            break;
                        case 't':
                            chatHub.server.sendMessageToTeacher(fromUserName, fromuserEnroll, toUserEnroll, msg);
                            break;
                        case 'g':
                            chatHub.server.sendMessageToGroup(fromUserName, fromuserEnroll, toGroupId , msg);
                            break;
                        
                        default:
                            alert('Select a field');
                    };
                 
                  //  chatHub.server.sendMessageToAll(userName, msg);
                    
                }
            });
     
            $('#classmates').click( function () {
                selectedfield = 'c';
               
                chatHub.server.loadRegisteredUsers("<%# this.UserEnrollNo %>");


                });
                $('#teachers').click(  function () {
                    selectedfield = 't';
                    chatHub.server.loadRegisteredTeachers();


                });

           /*$('#groups').onchange(function () {
             */   
               var selectBox = document.getElementById("select_user_type");
               selectBox.addEventListener('change', changeFunc);
               async  function changeFunc() {

                    if (this.value == 'Groups') {
                    /*alert(this.value);*/
                   selectedfield = 'g';
                        chatHub.server.loadRegisteredGroups(enrollno);
                    }
                    if (this.value == 'Classmates') {
                    /*alert(this.value);*/
                        selectedfield = 'c';
                        chatHub.server.loadRegisteredUsers("<%# this.UserEnrollNo %>");
                    }
                    if (this.value == 'Teachers') {
                    /*alert(this.value);*/
                        selectedfield = 't';
                        chatHub.server.loadRegisteredTeachers();
                    }
               }
           //});


     $('.rusers').mouseenter(  function () {
         var i;

         var ide = this.children;
         if (true) {
             for (i = 0; i < ide.length; i++) {
                 var num = ide.item(i).addEventListener('mouseup', function () {
                     console.log('event occured');




                     if (selectedfield == 'c') {

                         var toEnrollNo = this.id;
                         $('#hdtoUserEnroll').val(toEnrollNo);
                         console.log(toEnrollNo);
                         $('#spanUser').val = toEnrollNo;
                         chatHub.server.loadPrivateChat1(enrollno, toEnrollNo);
                         //loaded.push(toEnrollNo);
                     }
                     else if (selectedfield == 'g') {
                         toGroupId = this.id;



                         chatHub.server.loadGroupChat(toGroupId, enrollno);
                     }

                 });

             }

         }


     });

     //NOTIFICAIONS
     $('#notification').click(function () {
         console.log("notification clicked");
         var targetdiv = document.getElementById('notification-btn-target');
         targetdiv.style.display = "block";
         chatHub.server.showNotification();
     });


     $('#create-ntf').click( function () {

         var msg = $("#ntf-msg").val();
         $("#ntf-msg").val('');

         if (msg.length > 0) {
             var creator = name;
             var creatorEnrollNo = enrollno;
             var toDate = $('#to-date').val();
             console.log('creating notification');
             function sleep(milliseconds) {
                 const date = Date.now();
                 let currentDate = null;
                 do {
                     currentDate = Date.now();
                     console.log(currentDate.toString());
                 } while (currentDate - date < milliseconds);
             }
             sleep(10000);
             console.log('notification created');


             chatHub.server.createNotification(msg, creator, creatorEnrollNo, toDate);

         }
     });

                $('#self_pp_sm').click(function () {

                    console.log('success');
                    chatHub.server.getUserData("<%=Session["UserEnrollNo"].ToString()%>");
                });


                
     // Send Message on Enter Button
     $("#txtMessage").keypress(function (e) {
         if (e.which == 13) {
             $('#btnSendMsg').click();
         }
     });


                $('#exampleModal').on('show.bs.modal', function (event) {
                    var button = $(event.relatedTarget) // Button that triggered the modal
                    //var recipient = button.data('whatever') // Extract info from data-* attributes
                    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                    var modal = $(this)
                    modal.find('.modal-title').text('New Notification');
                    //modal.find('.modal-body input').val(recipient)
                });

     


 });



        };

        

    </script>




    <style>
      #app,
      body,
      html {
        height: 100%;
        width: 100%;
        overflow: hidden;
        padding: 0;
        margin: 0;
      }
      #app {
        position: absolute;
        top: 0;
        left: 0;
      }
      #initial_startup,
      #startup {
        width: 100%;
        height: 100%;
        position: fixed;
        background-color: #f0f0f0;
        -moz-user-select: none;
        -webkit-user-select: none;
        display: flex;
        align-items: center;
        justify-content: center;
        display: -webkit-box;
        display: -webkit-flex;
        -webkit-align-items: center;
        -webkit-justify-content: center;
        flex-direction: column;
        -webkit-flex-direction: column;
      }
      .spinner-container {
        -webkit-animation: rotate 2s linear infinite;
        animation: rotate 2s linear infinite;
        z-index: 2;
      }
      .spinner-path {
        stroke-dasharray: 1, 150;
        stroke-dashoffset: 0;
        stroke: #acb9bf;
        stroke-linecap: round;
        -webkit-animation: dash 1.5s ease-in-out infinite;
        animation: dash 1.5s ease-in-out infinite;
      }
      @keyframes rotate {
        100% {
          transform: rotate(360deg);
        }
      }
      @-webkit-keyframes rotate {
        100% {
          -webkit-transform: rotate(360deg);
        }
      }
      @keyframes dash {
        0% {
          stroke-dasharray: 1, 150;
          stroke-dashoffset: 0;
        }
        50% {
          stroke-dasharray: 90, 150;
          stroke-dashoffset: -35;
        }
        100% {
          stroke-dasharray: 90, 150;
          stroke-dashoffset: -124;
        }
      }
      @-webkit-keyframes dash {
        0% {
          stroke-dasharray: 1, 150;
          stroke-dashoffset: 0;
        }
        50% {
          stroke-dasharray: 90, 150;
          stroke-dashoffset: -35;
        }
        100% {
          stroke-dasharray: 90, 150;
          stroke-dashoffset: -124;
        }
      }
      .progress-container {
        width: 360px;
        position: fixed;
        padding-top: 120px;
        top: 50%;
        left: 50%;
        margin-left: -180px;
      }
      progress {
        -webkit-appearance: none;
        appearance: none;
        width: 100%;
        height: 3px;
        border: none;
        margin: 0;
        color: #00d9bb;
        background-color: #e6e6e6;
      }
      progress[value]::-webkit-progress-bar {
        background-color: #e6e6e6;
      }
      progress[value]::-webkit-progress-value {
        background-color: #00d9bb;
        transition: width 0.45s ease;
      }
      progress[value]::-moz-progress-bar {
        background-color: #00d9bb;
        transition: width 0.45s ease;
      }

      /* .testing{
        background-color: tomato;
      }
      .testing1{
        background-color: rgb(45, 221, 119);
      }
      .testing2{
        background-color: rgb(63, 50, 243);
      }
      .testing3{
        background-color: rgb(192, 238, 28);
      }
      .testing4{
        background-color: #acb9bf;
      } */

        _2A8P4 {
            box-shadow: 0 0 11px rgb(136 136 136);
            font-size: 20px;
        }


        .top-panel-bar {
            padding:15px;
            width: 1396px;
            background-color: rgb(250 245 216);
        }

        .panel-child{
            padding:5px;
        }

        .search-header-sm{
            box-shadow:0px 2px 2px 2px rgb(136, 136, 136);
        }

        ._1R3Un {
            padding: 10px 16px;
            background-color: white;
        }
        .chat-box{
             left: 0;
    border-left: 1px solid var(--conversation-panel-border);
    background-color:white;
    
        }

      .urow{
        transition: box-shadow 0.09s;
        display: flex;
        flex-direction: row;
        height: 60px;
        border-bottom-color: black;
        border-bottom-width: 5px;
        border-radius: 0px;
        padding-top: 10px;
        padding-left: 5px;
      }
      .urow:hover{
        box-shadow: 0 0 11px rgb(136, 136, 136);
        /* color: ;  */
      }
        
._3QfZd {
  position: relative;
  top: 0;
  display: flex;
  width: 80%;
  height: 100%;
  overflow: hidden;
}
html[dir=ltr] ._3QfZd {
    left: 10vw;
    background-position: 0 0;
    
}
@media screen and (min-width:1441px) {
    .app-wrapper-web ._3QfZd {
        top: 19px;
        width: 1000px;
        height: 90%;
    }

    html[dir] .app-wrapper-web ._3QfZd {
       
        box-shadow: 0 1px 1px 0 rgba(var(--shadow-rgb),.06),0 2px 5px 0 rgba(var(--shadow-rgb),.2)
    }

    html[dir] .app-wrapper-web.safari-fix ._3QfZd {
        border-radius: 4px
    }
}

.profile-image {
    margin-top: 7px;
    height: 30px;
    width: 30px;
}

            .chat-list-header{
                box-shadow: 0px 3px 5px 1px #ccc;
            }
        
        .chat-header {
            padding: 10px 16px;
            
            box-shadow: 0px 3px 5px 1px #ccc;
            background-color: white;
        }

      .name-row{
        padding-top: 3px;
        font-size: 20px;
        display: flex;
        flex-direction:row;
        width: 100%;
        height:50%;
        
      }
      .uunread{
        padding: 3px;
        height: 18px;
        font-size: 15px;
       background-color: red;
       color:white;
       border-radius: 10px;
      }
      .udetails-sm{
        padding-left: 5px;
        padding-right: 5px;
        display: flex;
        flex-direction: column;
        height: 100%;
        width:100%;
      }
      .pp-sm{
        padding: 5px;
        height: 50px;
        width:50px;
        border-radius: 10px;
        display: flex;
        flex-direction: row;
        float: left;
      }
     
      .img-pp-sm{
          transition: box-shadow 0.1s;
        border-radius: 10px;
        height:50px;
        width:50px;
        
      }
       .img-pp-sm:hover{
         box-shadow: 0 0 11px rgb(136, 136, 136);
      }
      .ulast-chat{
        padding-left: 5px;
        padding-top: 3px;
        display: flex;
        flex-direction: row;
        
        height:50%;
      }
      .hr{
        height:1px;
        background-color:bisque;
      }

      html[dir] ._1gL0z {
          background-color:white;
      }

        .sender-msg-box {
            display: flex;
            flex-direction: row;
            padding: 10px;
        }

        .receiver-msg-box {
            display: flex;
            flex-direction: row-reverse;
            padding: 10px;
        }

        .msg-box-row {
            display: flex;
            flex-direction: row;
        }

        .msg {
            color:black;
            font-size: 20px;
        }

        .sender-box{
            box-shadow: 0 0 11px rgb(136, 136, 136);
            padding: 20px;
            background-color: rgb(255, 251, 240);
            border-radius: 20px;
            border-top-left-radius: 0px;
        }

        .sender-msg-time-read-rec {
            display: flex;
            flex-direction: row;
        }

        .msg-time {
            font-size: 14px;
            font-weight: 20;
        }

        .receiver-box{
            box-shadow: 0 0 11px rgb(136, 136, 136);
            padding: 20px;
            background-color: rgb(54, 142, 243);
            border-radius: 20px;
            border-bottom-right-radius: 0px;
            
        }

        .receiver-msg-time-read-rec {
            display: flex;
            flex-direction: row-reverse;
        }


        
 ._2A8P4 {
    padding: 9px 12px 11px;
    margin: 5px 10px;
    background-color: var(--compose-input-background);
    border: 1px solid var(--compose-input-border);
    border-radius: 21px;
    box-shadow: 0 0 11px rgb(136, 136, 136);
}

 .fa-bell:before {
    
    width:40px;
    height:40px;
}

 /*
        .darkable{
            background-color:black;
            color:white;
        }
*/
        
    </style>
    <link
      href="./WhatsApp_files/bootstrap_qr-e892ca30934b9f1b9db6.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="./WhatsApp_files/bootstrap_main.4901d46d1d36a610ddfc.css"
    />
      
    <style id="asset-style" type="text/css"></style>
    <link
      rel="stylesheet"
      type="text/css"
      href="./WhatsApp_files/lazy_loaded_high_priority_components_lazy_loaded_low_priority_components.fc5b5a8da2673c56e501.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="./WhatsApp_files/lazy_loaded_high_priority_components.73ec82359679ea8b20b9.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="./WhatsApp_files/lazy_loaded_low_priority_components.c9e655ed9d61a3f90746.css"
    />
    <link
      id="favicon"
      rel="shortcut icon"
      type="image/png"
      href="https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png"
      src="/img/favicon_c5088e888c97ad440a61d247596f88e5.png"
    />

  </head>
  <body class="web">
      <form id="form1" runat="server">
    
    <div id="app">
      <div tabindex="-1" id="for_background" class="_3h3LX _34ybp app-wrapper-web font-fix os-win">
        <span></span><span></span><span></span><span></span><span></span>
        
          <!-- hidden data -->
            <input id="hdId" type="hidden" />
                <input id="PWCount" type="hidden" value="info" />
                <input id="hdUserEnroll" type="hidden" />
                <input id="hdtoUserEnroll" type="hidden" />
                
          <div style="width:1396px; height:100vh; display:flex; flex-direction:column;">

              
              


        <div tabindex="-1" class="_3QfZd two">
          
          <div class="_3-dtC"></div>
          <div class="Akuo4">
            <div class="_1Flk2 _2DPZK"></div>
            <div class="_1Flk2 _1sFTb"><span class="_2zn9Y"></span></div>
            <div class="_1Flk2 _3xysY"><span class="_2zn9Y"></span></div>
          </div>
          
          <div class="_1Flk2 _2DPZK">
            <div id="side" class="_3U29Q">
              <header class="chat-list-header darkable _1R3Un">
                  <div  class="profile-header " style="display: flex; flex-direction: row;">
                      <div id="self_pp_sm" class="pp-sm-box" style="display: flex; justify-content: center;">
                          <img  src="<%= UserImage %>" alt="" class="profile-image rounded-circle float-left" />
                      </div>
                      
                  </div>
                  <div style="display:flex;height:40px;width:90%; flex-direction:row-reverse;">
                      <div id="notification" style="display:flex; height:40px; width:40px; ">
                          <script>
                              function open_notices() {
                                 
                              }

                          </script>
                         <svg id="line_icons" height="40px" viewBox="0 0 74 74" width="40px" xmlns="http://www.w3.org/2000/svg" data-name="line icons"><path d="m60.661 25.336h-12.342a1 1 0 0 1 -1-1v-12.336a1 1 0 0 1 1.707-.707l12.342 12.336a1 1 0 0 1 -.707 1.707zm-11.342-2h8.928l-8.928-8.927z"/><path d="m60.659 72h-47.32a1 1 0 0 1 -1-1l.02-59.01a1 1 0 0 1 1-1h5.85a1 1 0 0 1 0 2h-4.85l-.02 57.01h45.32v-45.253l-11.754-11.754h-20.856a1 1 0 0 1 0-2h21.27a1 1 0 0 1 .707.293l12.34 12.339a1 1 0 0 1 .293.708v46.667a1 1 0 0 1 -1 1z"/><path d="m54.49 39.683h-34.982a1 1 0 0 1 0-2h34.982a1 1 0 0 1 0 2z"/><path d="m54.49 47.683h-34.982a1 1 0 0 1 0-2h34.982a1 1 0 0 1 0 2z"/><path d="m54.49 55.683h-34.982a1 1 0 0 1 0-2h34.982a1 1 0 0 1 0 2z"/><path d="m54.49 63.683h-34.982a1 1 0 0 1 0-2h34.982a1 1 0 0 1 0 2z"/><path d="m19.1 23.6a1 1 0 0 1 -.986-.83 8.752 8.752 0 0 1 5.59-9.357 8.752 8.752 0 0 1 10.53 2.815 1 1 0 0 1 -.449 1.492l-14.308 5.81a1.006 1.006 0 0 1 -.377.07zm8.17-8.887a7.477 7.477 0 0 0 -2.814.554 6.942 6.942 0 0 0 -4.445 5.884l11.735-4.762a6.578 6.578 0 0 0 -4.475-1.673z"/><path d="m21.021 17.461a1 1 0 0 1 -.926-.624l-2.606-6.42a1 1 0 0 1 .551-1.3l6.727-2.73a1 1 0 0 1 1.3.551l2.6 6.413a1 1 0 0 1 -1.854.752l-2.221-5.49-4.873 1.978 2.229 5.494a1 1 0 0 1 -.927 1.376z"/><path d="m30.768 31.817a1 1 0 0 1 -.8-.395l-7.518-9.9a1 1 0 0 1 .42-1.532l6.011-2.439a1 1 0 0 1 1.368.8l1.511 12.349a1 1 0 0 1 -.616 1.048 1.014 1.014 0 0 1 -.376.069zm-5.932-10.463 4.49 5.913-.9-7.37z"/><path d="m18.418 11.04a.994.994 0 0 1 -.446-.1l-4.088-2.046a1 1 0 0 1 .07-1.822l12.324-5a1 1 0 0 1 1.322 1.256l-1.51 4.313a1 1 0 0 1 -.567.6l-6.727 2.73a1 1 0 0 1 -.378.069zm-1.66-2.947 1.7.85 5.889-2.39.629-1.8z"/></svg>
                      </div>
                      <div id="notification-btn-target" style="height:500px;width:500px; background-color:brown; display:none">
                          <button type="button" onclick="close_notices()">close</button>
                          <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" >
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div id="ntf">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                          <script>
                              function close_notices() {
                                  var targetdiv = document.getElementById('notification-btn-target');
                                  targetdiv.style.display = "none";
                              }
                          </script>
                      </div>
                      <button type="button" onclick="open_add_notice()" id="notice-plus-btn" class="btn btn-primary" >+</button>
                      <script>
                          function open_add_notice() {
                              var targetdiv = document.getElementById('notice-plus-btn-target');
                              targetdiv.style.display = "block";
                          }


                      </script>
                      <div id="notice-plus-btn-target" style="height:500px;width:500px; display:none; background-color:cadetblue">
                          <button type="button" onclick="close_add_notice()">close</button>
                          <script>
                              function close_add_notice() {
                                  {
                                      var targetdiv = document.getElementById('notice-plus-btn-target');
                                      targetdiv.style.display = "none";
                                  }
                              }
                          </script>

                          <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">New Notification</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form>

                                            <div class="form -group">
                                                <label for="to-date" class="col-form-label">ExpireDate:</label>
                                                <input type="datetime-local" class="form-control" id="to-date" />
                                            </div>


                                            <div class="form-group">
                                                <label for="message-text" class="col-form-label">Message:</label>
                                                <textarea class="form-control" id="ntf-msg"></textarea>
                                            </div>

                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button id="create-ntf" type="button" class="btn btn-primary">Create Notification</button>
                                    </div>
                                </div>

                      </div>
                      </div>
                                   

              </header>
              
              
              <div class="search-in-users" style="display:flex; flex-direction:row; width:100%; height:50px; background-color:#e8e8e8">

                  <div class="ddlist" style="display:flex; height:40px;width:40%; background-color:white;border-radius:10px;padding-left:20px;font-size:20px;">

                      <select id="select_user_type" name="D1" >
                          <option id="classmates" class="user-option">Classmates</option>
                          <option id="teachers" class="user-option">Teachers</option>
                          <option id="groups" class="user-option">Groups</option>
                          
                      </select>

                  </div>
                  <div>
                          <input type="text" id="user_search" onkeyup="searchuser()" placeholder="Enter Name "/>
                          <script>
                              function searchuser() {

                                  var input, filter, ul, li, a, i, txtValue;
                                  input = document.getElementById('user_search');
                                  filter = input.value.toUpperCase();
                                  ul = document.getElementById("listarea");
                                  li = ul.getElementsByClassName('urow');
                                  for (i = 0; i < li.length; i++) {
                                      a = li[i].getElementsByClassName('uname')[0];
                                      txtValue = a.textContent || a.innerText;
                                      if (txtValue.toUpperCase().indexOf(filter) > -1) {
                                          li[i].style.display = "";
                                      } else {
                                          li[i].style.display = "none";
                                      }
                                  }
                              }
                          </script>
                      </div>

              </div>
              <div class="_1C2Q3 F-0gY" id="pane-side">
                <div tabindex="-1" data-tab="4">
                  <div class="" style="pointer-events: auto">
                      
                      <div id="list_area" style="width:100%;height:1000px; background-color:aqua; display:none;">
                          
                            <asp:TextBox ID="TextBox8" placeholder="new username" runat="server"></asp:TextBox>
                            <asp:TextBox ID="TextBox9" placeholder="new password" runat="server"></asp:TextBox>
                          
                            <asp:TextBox ID="TextBox10" placeholder="new email" runat="server"></asp:TextBox>
                          <asp:Button ID="UpdateDetails" runat="server" OnClick="UpdateDetails_Click" Text="Button" />
                       &nbsp;
                      </div>
                      
                    <div id="listarea"
                      class="rusers JnmQF _3QmOg"   style="height: 1000px;">
                   
                      
                    </div>
                  </div>
                </div>
                <div hidden="" style="display: none"></div>
                <div class="_3q7pL"></div>
              </div>
            </div>
          </div>
          <div class="_1Flk2 _1sFTb">
            <div id="main" class="_3AUV4">
              <div
                class="IeYBo"
                data-asset-chat-background-light="true"
                style="opacity: 0.06"
              ></div>
              <header class="_1-qgF chat-header darkable" style="border-left-width:2px; border-left-color:rgb(147 147 147);">
                <div class="fBf_N" role="button">
                  <div class="-y4n1" style="height: 40px; width: 40px">
                    <div class="_27MZN">
                      <span
                        data-testid="default-user"
                        data-icon="default-user"
                        class=""
                        ><svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 212 212"
                          width="212"
                          height="212"
                        >
                          <path
                            fill="#DFE5E7"
                            class="background"
                            d="M106.251.5C164.653.5 212 47.846 212 106.25S164.653 212 106.25 212C47.846 212 .5 164.654.5 106.25S47.846.5 106.251.5z"
                          ></path>
                          <path
                            fill="#FFF"
                            class="primary"
                            d="M173.561 171.615a62.767 62.767 0 0 0-2.065-2.955 67.7 67.7 0 0 0-2.608-3.299 70.112 70.112 0 0 0-3.184-3.527 71.097 71.097 0 0 0-5.924-5.47 72.458 72.458 0 0 0-10.204-7.026 75.2 75.2 0 0 0-5.98-3.055c-.062-.028-.118-.059-.18-.087-9.792-4.44-22.106-7.529-37.416-7.529s-27.624 3.089-37.416 7.529c-.338.153-.653.318-.985.474a75.37 75.37 0 0 0-6.229 3.298 72.589 72.589 0 0 0-9.15 6.395 71.243 71.243 0 0 0-5.924 5.47 70.064 70.064 0 0 0-3.184 3.527 67.142 67.142 0 0 0-2.609 3.299 63.292 63.292 0 0 0-2.065 2.955 56.33 56.33 0 0 0-1.447 2.324c-.033.056-.073.119-.104.174a47.92 47.92 0 0 0-1.07 1.926c-.559 1.068-.818 1.678-.818 1.678v.398c18.285 17.927 43.322 28.985 70.945 28.985 27.678 0 52.761-11.103 71.055-29.095v-.289s-.619-1.45-1.992-3.778a58.346 58.346 0 0 0-1.446-2.322zM106.002 125.5c2.645 0 5.212-.253 7.68-.737a38.272 38.272 0 0 0 3.624-.896 37.124 37.124 0 0 0 5.12-1.958 36.307 36.307 0 0 0 6.15-3.67 35.923 35.923 0 0 0 9.489-10.48 36.558 36.558 0 0 0 2.422-4.84 37.051 37.051 0 0 0 1.716-5.25c.299-1.208.542-2.443.725-3.701.275-1.887.417-3.827.417-5.811s-.142-3.925-.417-5.811a38.734 38.734 0 0 0-1.215-5.494 36.68 36.68 0 0 0-3.648-8.298 35.923 35.923 0 0 0-9.489-10.48 36.347 36.347 0 0 0-6.15-3.67 37.124 37.124 0 0 0-5.12-1.958 37.67 37.67 0 0 0-3.624-.896 39.875 39.875 0 0 0-7.68-.737c-21.162 0-37.345 16.183-37.345 37.345 0 21.159 16.183 37.342 37.345 37.342z"
                          ></path></svg
                      ></span>
                    </div>
                  </div>
                </div>
                <div class="_2uaUb" role="button">
                  <div class="z4t2k">
                    <div class="_2KQyF">
                      <span id="spanUser1"
                        dir="auto"
                        title="Pushkar Joshi GECA"
                        class="darkable _35k-1 _1adfa _3-8er"
                        >Pushkar Joshi GECA</span
                      >
                    </div>
                  </div>
                </div>
                <div class="_1IeOz">
                  <div class="_1ljzS pnYZD">
                    <div class="_2n-zq">
                      <div
                        aria-disabled="false"
                        role="button"
                        tabindex="0"
                        data-tab="8"
                        title="Search…"
                        aria-label="Search…"
                      >
                        <span
                          data-testid="search-alt"
                          data-icon="search-alt"
                          class=""
                          ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                          >
                            <path
                              fill="currentColor"
                              d="M15.9 14.3H15l-.3-.3c1-1.1 1.6-2.7 1.6-4.3 0-3.7-3-6.7-6.7-6.7S3 6 3 9.7s3 6.7 6.7 6.7c1.6 0 3.2-.6 4.3-1.6l.3.3v.8l5.1 5.1 1.5-1.5-5-5.2zm-6.2 0c-2.6 0-4.6-2.1-4.6-4.6s2.1-4.6 4.6-4.6 4.6 2.1 4.6 4.6-2 4.6-4.6 4.6z"
                            ></path></svg
                        ></span>
                      </div>
                      <span></span>
                    </div>
                    <div class="_2n-zq">
                      <div
                        aria-disabled="false"
                        role="button"
                        tabindex="0"
                        data-tab="8"
                        title="Menu"
                        aria-label="Menu"
                      >
                        <span data-testid="menu" data-icon="menu" class=""
                          ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                          >
                            <path
                              fill="currentColor"
                              d="M12 7a2 2 0 1 0-.001-4.001A2 2 0 0 0 12 7zm0 2a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 9zm0 6a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 15z"
                            ></path></svg
                        ></span>
                      </div>
                      <span></span>
                    </div>
                  </div>
                </div>
              </header>
              <span class="_1C6f8"></span>
              <div class="_1C6f8"><span></span></div>
              <div class="_2wjK5">
                <div class="_3wXwX copyable-area">
                  <span></span><span></span>
                  <div class="_1gL0z chat-back-screen darkable" tabindex="0">
                    <div class="_2VvGi"></div>
                    <div class="_2hDby">
                      <div class="_3M4BR" title="load earlier messages…">
                        <span data-testid="refresh" data-icon="refresh" class=""
                          ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                          >
                            <path
                              fill="currentColor"
                              d="M17.6 6.4C16.2 4.9 14.2 4 12 4c-4.4 0-8 3.6-8 8s3.6 8 8 8c3.7 0 6.8-2.6 7.7-6h-2.1c-.8 2.3-3 4-5.6 4-3.3 0-6-2.7-6-6s2.7-6 6-6c1.7 0 3.1.7 4.2 1.8L13 11h7V4l-2.4 2.4z"
                            ></path></svg
                        ></span>
                      </div>
                    </div>
                    <div id="msgarea" tabindex="-1" class="_11liR darkablecaht">
                      <!-- msg list area -->
                        



                    </div>
                    <div hidden="" style="display: none"></div>
                  </div>
                </div>
              </div>
              <div class="_2sw49" style="height: 0px"></div>
              <footer tabindex="-1" class="_3uxr9">
                <div class="vR1LG _3wXwX copyable-area darkable">
                  <div class="EBaI7 _23e-h">
                    <div data-state="closed" class="_291Eb _2MeuX">
                      <button
                        tabindex="-1"
                        class="_3k0dC _2zMTD _3js56 rjHB8"
                        aria-label="Close panel"
                      >
                        <span data-testid="x" data-icon="x" class=""
                          ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                          >
                            <path
                              fill="currentColor"
                              d="M19.1 17.2l-5.3-5.3 5.3-5.3-1.8-1.8-5.3 5.4-5.3-5.3-1.8 1.7 5.3 5.3-5.3 5.3L6.7 19l5.3-5.3 5.3 5.3 1.8-1.8z"
                            ></path></svg
                        ></span></button
                      ><button
                        tabindex="-1"
                        class="_3k0dC _2zMTD _2NHIO _15ScS VRn4o"
                        aria-label="Open emojis panel"
                        data-tab="5"
                      >
                        <span data-testid="smiley" data-icon="smiley" class=""
                          ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                          >
                            <path
                              fill="currentColor"
                              d="M9.153 11.603c.795 0 1.439-.879 1.439-1.962s-.644-1.962-1.439-1.962-1.439.879-1.439 1.962.644 1.962 1.439 1.962zm-3.204 1.362c-.026-.307-.131 5.218 6.063 5.551 6.066-.25 6.066-5.551 6.066-5.551-6.078 1.416-12.129 0-12.129 0zm11.363 1.108s-.669 1.959-5.051 1.959c-3.505 0-5.388-1.164-5.607-1.959 0 0 5.912 1.055 10.658 0zM11.804 1.011C5.609 1.011.978 6.033.978 12.228s4.826 10.761 11.021 10.761S23.02 18.423 23.02 12.228c.001-6.195-5.021-11.217-11.216-11.217zM12 21.354c-5.273 0-9.381-3.886-9.381-9.159s3.942-9.548 9.215-9.548 9.548 4.275 9.548 9.548c-.001 5.272-4.109 9.159-9.382 9.159zm3.108-9.751c.795 0 1.439-.879 1.439-1.962s-.644-1.962-1.439-1.962-1.439.879-1.439 1.962.644 1.962 1.439 1.962z"
                            ></path></svg
                        ></span></button
                      ><button
                        tabindex="-1"
                        class="_3k0dC _2zMTD igz8o VRn4o"
                        aria-label="Open gif panel"
                      >
                        <span data-testid="gif" data-icon="gif" class=""
                          ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                          >
                            <path
                              fill="currentColor"
                              d="M13.177 12.013l-.001-.125v-.541-.512c0-.464 0-.827-.002-1.178a.723.723 0 0 0-.557-.7.715.715 0 0 0-.826.4c-.05.115-.072.253-.073.403-.003 1.065-.003 1.917-.002 3.834v.653c0 .074.003.136.009.195a.72.72 0 0 0 .57.619c.477.091.878-.242.881-.734.002-.454.003-.817.002-1.633l-.001-.681zm-3.21-.536a35.751 35.751 0 0 0-1.651-.003c-.263.005-.498.215-.565.48a.622.622 0 0 0 .276.7.833.833 0 0 0 .372.104c.179.007.32.008.649.005l.137-.001v.102c-.001.28-.001.396.003.546.001.044-.006.055-.047.081-.242.15-.518.235-.857.275-.767.091-1.466-.311-1.745-1.006a2.083 2.083 0 0 1-.117-1.08 1.64 1.64 0 0 1 1.847-1.41c.319.044.616.169.917.376.196.135.401.184.615.131a.692.692 0 0 0 .541-.562c.063-.315-.057-.579-.331-.766-.789-.542-1.701-.694-2.684-.482-2.009.433-2.978 2.537-2.173 4.378.483 1.105 1.389 1.685 2.658 1.771.803.054 1.561-.143 2.279-.579.318-.193.498-.461.508-.803.014-.52.015-1.046.001-1.578-.009-.362-.29-.669-.633-.679zM18 4.25H6A4.75 4.75 0 0 0 1.25 9v6A4.75 4.75 0 0 0 6 19.75h12A4.75 4.75 0 0 0 22.75 15V9A4.75 4.75 0 0 0 18 4.25zM21.25 15A3.25 3.25 0 0 1 18 18.25H6A3.25 3.25 0 0 1 2.75 15V9A3.25 3.25 0 0 1 6 5.75h12A3.25 3.25 0 0 1 21.25 9v6zm-2.869-6.018H15.3c-.544 0-.837.294-.837.839V14.309c0 .293.124.525.368.669.496.292 1.076-.059 1.086-.651.005-.285.006-.532.004-1.013v-.045l-.001-.46v-.052h1.096l1.053-.001a.667.667 0 0 0 .655-.478c.09-.298-.012-.607-.271-.757a.985.985 0 0 0-.468-.122 82.064 82.064 0 0 0-1.436-.006h-.05l-.523.001h-.047v-1.051h1.267l1.22-.001c.458-.001.768-.353.702-.799-.053-.338-.35-.56-.737-.561z"
                            ></path></svg
                        ></span></button
                      ><button
                        tabindex="-1"
                        class="_3k0dC _2zMTD kwzXH VRn4o"
                        aria-label="Open sticker panel"
                      >
                        <span data-testid="sticker" data-icon="sticker" class=""
                          ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                          >
                            <path
                              fill="currentColor"
                              d="M21.799 10.183c-.002-.184-.003-.373-.008-.548-.02-.768-.065-1.348-.173-1.939a6.6 6.6 0 0 0-.624-1.87 6.24 6.24 0 0 0-1.171-1.594 6.301 6.301 0 0 0-1.614-1.159 6.722 6.722 0 0 0-1.887-.615c-.59-.106-1.174-.15-1.961-.171-.318-.008-3.607-.012-4.631 0-.798.02-1.383.064-1.975.17a6.783 6.783 0 0 0-1.888.616 6.326 6.326 0 0 0-2.785 2.753 6.658 6.658 0 0 0-.623 1.868c-.107.591-.152 1.186-.173 1.941-.008.277-.016 2.882-.016 2.882 0 .52.008 1.647.016 1.925.02.755.066 1.349.172 1.938.126.687.33 1.3.624 1.871.303.59.698 1.126 1.173 1.595a6.318 6.318 0 0 0 1.614 1.159 6.786 6.786 0 0 0 2.146.656c.479.068.833.087 1.633.108.035.001 2.118-.024 2.578-.035a6.873 6.873 0 0 0 4.487-1.811 210.877 210.877 0 0 0 2.928-2.737 6.857 6.857 0 0 0 2.097-4.528l.066-1.052.001-.668c.001-.023-.005-.738-.006-.755zm-3.195 5.92c-.79.757-1.784 1.684-2.906 2.716a5.356 5.356 0 0 1-2.044 1.154c.051-.143.116-.276.145-.433.042-.234.06-.461.067-.74.003-.105.009-.789.009-.789.013-.483.042-.865.107-1.22.069-.379.179-.709.336-1.016.16-.311.369-.595.621-.844.254-.252.542-.458.859-.617.314-.158.65-.268 1.037-.337a8.127 8.127 0 0 1 1.253-.106s.383.001.701-.003a4.91 4.91 0 0 0 .755-.066c.186-.034.348-.105.515-.169a5.35 5.35 0 0 1-1.455 2.47zm1.663-4.757a1.128 1.128 0 0 1-.615.859 1.304 1.304 0 0 1-.371.119 3.502 3.502 0 0 1-.52.043c-.309.004-.687.004-.687.004-.613.016-1.053.049-1.502.129a5.21 5.21 0 0 0-1.447.473 4.86 4.86 0 0 0-2.141 2.115 5.088 5.088 0 0 0-.479 1.434 9.376 9.376 0 0 0-.131 1.461s-.006.684-.008.777c-.006.208-.018.37-.043.511a1.154 1.154 0 0 1-.626.86c-.072.036-.168.063-.37.098-.027.005-.25.027-.448.031-.021 0-1.157.01-1.192.009-.742-.019-1.263-.046-1.668-.126a5.27 5.27 0 0 1-1.477-.479 4.823 4.823 0 0 1-2.127-2.1 5.141 5.141 0 0 1-.482-1.453c-.09-.495-.13-1.025-.149-1.71a36.545 36.545 0 0 1-.012-.847c-.003-.292.005-3.614.012-3.879.02-.685.061-1.214.151-1.712a5.12 5.12 0 0 1 .481-1.45c.231-.449.53-.856.892-1.213.363-.36.777-.657 1.233-.886a5.26 5.26 0 0 1 1.477-.479c.503-.09 1.022-.129 1.74-.149a342.03 342.03 0 0 1 4.561 0c.717.019 1.236.058 1.737.148a5.263 5.263 0 0 1 1.476.478 4.835 4.835 0 0 1 2.126 2.098c.228.441.385.913.482 1.453.091.499.131 1.013.15 1.712.008.271.014 1.098.014 1.235a2.935 2.935 0 0 1-.037.436z"
                            ></path></svg
                        ></span>
                      </button>
                    </div>
                    <div class="_2C9f1">
                      <div class="_2n-zq">
                        <div
                          aria-disabled="false"
                          role="button"
                          tabindex="0"
                          title="Attach"
                          aria-label="Attach"
                        >
                          <span data-testid="clip" data-icon="clip" class=""
                            ><svg
                              xmlns="http://www.w3.org/2000/svg"
                              viewBox="0 0 24 24"
                              width="24"
                              height="24"
                            >
                              <path
                                fill="currentColor"
                                d="M1.816 15.556v.002c0 1.502.584 2.912 1.646 3.972s2.472 1.647 3.974 1.647a5.58 5.58 0 0 0 3.972-1.645l9.547-9.548c.769-.768 1.147-1.767 1.058-2.817-.079-.968-.548-1.927-1.319-2.698-1.594-1.592-4.068-1.711-5.517-.262l-7.916 7.915c-.881.881-.792 2.25.214 3.261.959.958 2.423 1.053 3.263.215l5.511-5.512c.28-.28.267-.722.053-.936l-.244-.244c-.191-.191-.567-.349-.957.04l-5.506 5.506c-.18.18-.635.127-.976-.214-.098-.097-.576-.613-.213-.973l7.915-7.917c.818-.817 2.267-.699 3.23.262.5.501.802 1.1.849 1.685.051.573-.156 1.111-.589 1.543l-9.547 9.549a3.97 3.97 0 0 1-2.829 1.171 3.975 3.975 0 0 1-2.83-1.173 3.973 3.973 0 0 1-1.172-2.828c0-1.071.415-2.076 1.172-2.83l7.209-7.211c.157-.157.264-.579.028-.814L11.5 4.36a.572.572 0 0 0-.834.018l-7.205 7.207a5.577 5.577 0 0 0-1.645 3.971z"
                              ></path></svg
                          ></span>
                        </div>
                        <span></span>
                      </div>
                    </div>
                  </div>
                  <div tabindex="-1" class="_2A8P4 darkable" >
                    <div tabindex="-1" class="_1JAUF _2x4bz"><div class="OTBsx" style="visibility: hidden">Type a message</div><div id="txtMessage" class="darkable _2_1wd copyable-text selectable-text" contenteditable="true" data-tab="6" placeholder="typesomething" dir="ltr" spellcheck="true"></div></div>

                  </div>
                  
                          <div id="btnSendMsg" style="display:flex; height:40px;width:40px; ">
                              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M1.101 21.757L23.8 12.028 1.101 2.3l.011 7.912 13.623 1.816-13.623 1.817-.011 7.912z"></path></svg>
                          </div>
                      
                    
                </div>
                <div class="_1gNA1">
                  <div class="-fxbk">
                    <div class="_1C2Q3"><div class="_3q7pL"></div></div>
                    <div class="_1C2Q3"><div class="_3q7pL"></div></div>
                    <div class="_1C2Q3"><div class="_3q7pL"></div></div>
                    <div class="_1C2Q3"><div class="_3q7pL"></div></div>
                    <div class="_1C2Q3"><div class="_3q7pL"></div></div>
                    <div class="_1C2Q3"><div class="_3q7pL"></div></div>
                  </div>
                </div>
                <div class="_1xPrU"></div>
                <div class="_1p9lF"></div>
              </footer>
              <div hidden="" style="display: none"></div>
              <span></span>
            </div>
            <div hidden="" style="display: none"></div>
          </div>
        </div>

              </div>

        <div hidden="" style="display: none"></div>
      </div>
      <div hidden="" style="display: none"></div>
    </div>
      </form>
  </body>
</html>
